spring:
  # 개발 환경 데이터베이스 설정
  datasource:
    url: jdbc:mysql://localhost:3306/nextstep_dev?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5

  # 개발환경 JPA 상세 설정
  jpa:
    hibernate:
      ddl-auto: update # 개발환경에서는 테이블 자동 생성/수정
    properties:
      hibernate:
        "[format_sql]": true
        "[show_sql]": true
    show-sql: true

# 개발환경 로깅 (더 상세하게)
logging:
  level:
    root: INFO
    "[web.mvc]": DEBUG
    "[org.springframework.web]": DEBUG
    "[org.hibernate.SQL]": DEBUG
    "[org.hibernate.type.descriptor.sql.BasicBinder]": TRACE
